# application.yaml
# Server settings (ServerProperties)
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

# DB
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hk-rest-ms?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

# JPA
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: rg.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true


# OUTPUT
  output:
      ansi:
        enabled: always # Configure the ANSI output (can be "detect", "always", "never").

# MyBatis
mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml

#debug: true

# Logger
logging:
  level:
    com.team.hk: debug
#  path: E://logs/logs.log
